# Generated by using Rcpp::compileAttributes() -> do not edit by hand
# Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

dance338 <- function(x) {
    .Call(`_pkg338_dance338`, x)
}

polyfit338 <- function(data, response, degree) {
    .Call(`_pkg338_polyfit338`, data, response, degree)
}

linfit338 <- function(x, y) {
    .Call(`_pkg338_linfit338`, x, y)
}

